### ISSUE TITLE
Command line option "keep-first-frame" not working

### ISSUE THREAD

**Issue by ulibuck** [gpx-animator/gpx-animator#498]
Hi
Thank you for GPX Animator.

With GPX Animator 1.8.0 I try to use `--keep-first-frame` as command line option but get the following error message

java.lang.AssertionError
	at app.gpx_animator.ui.cli.CommandLineConfigurationFactory.<init>(CommandLineConfigurationFactory.java:208)
	at app.gpx_animator.Main.start(Main.java:55)
	at app.gpx_animator.Main.main(Main.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:69)
	at install4j.app.gpx_animator.Main.main(Unknown Source)

My command is like this
`gpx-animator --attribution "blabla" --attribution-position "top left" --background-map-visibility 1.0 --speedup 667 --keep-first-frame 2000 --tms-url-template "https://{switch:a,b,c}.tile.opentopomap.org/{zoom}/{x}/{y}.png" --width 2560 --height 1440 --marker-size 15 --line-width 5 --pre-draw-track --pre-draw-track-color "#CD853F" --color "#CC0000" --font Monospaced-Normal-26 --input "20230212-083111.gpx" --output "20230212-083111.mp4"`

Without `--keep-first-frame` on the command line the error message is gone, yet the first frame is not kept.

**Comment by McPringle** [comment]
Thank you very much for your report. Indeed, this command line option is not correctly parsed. I will fix it ASAP.

**Comment by McPringle** [comment]
This bug is now fixed. The next release 1.8.1 will be published soon. Meanwhile, please use the graphical UI instead of the command line option. Sorry for the inconvenience.

**Comment by ulibuck** [comment]
Thank you for your fast response and for fixing the bug.
I am looking forward to the next release 1.8.1 of GPX Animator.
