### ISSUE TITLE
Error after Update to 1.8.2

### ISSUE THREAD

**Issue by bradl65** [gpx-animator/gpx-animator#552]
java.lang.NullPointerException: Cannot invoke "java.awt.geom.Point2D.getX()" because "marker" is null
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.awt.geom.Point2D.getX()" because "marker" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at app.gpx_animator.ui.swing.MainFrame$5.done(MainFrame.java:503)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Cannot invoke "java.awt.geom.Point2D.getX()" because "marker" is null
	at app.gpx_animator.core.renderer.Renderer.applyViewport(Renderer.java:364)
	at app.gpx_animator.core.renderer.Renderer.renderFrames(Renderer.java:287)
	at app.gpx_animator.core.renderer.Renderer.render(Renderer.java:183)
	at app.gpx_animator.ui.swing.MainFrame$5.doInBackground(MainFrame.java:471)
	at app.gpx_animator.ui.swing.MainFrame$5.doInBackground(MainFrame.java:468)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by bradl65** [comment]
World: Wikimedia Map is not loading

**Comment by McPringle** [comment]
I was not able to reproduce your problem. I need more information, please:

- Which OS are you using?
- Did you install GPX Animator using the Installer or the JAR file?
- Do you run GPX Animator using the command cline interface or as a GUI application?
- Save your configuration (File > Save as)
- Create a ZIP file with your saved configuration and your GPX file(s)
- Attach the ZIP file here or send it via mail to marcus@fihlon.swiss and mention "GPX Animator Issue # 552" in the subject

Maybe I will be able to reproduce your problem when I am using your configuration and files.

**Comment by McPringle** [comment]
> World: Wikimedia Map is not loading

When you access https://maps.wikimedia.org/osm-intl using a browser, you will get the reason:

> Error: 403, Forbidden: Map tiles are restricted to Wikimedia & affiliated sites only. See https://wikitech.wikimedia.org/wiki/Maps/External_usage

I can't do anything to solve the issue. It's a decision of the Wikimedia Foundation who will get access to their map data.

Next time please create a second issue because it has nothing to do with your original problem. That will make issue management easier. Thanks!
